"""PatchBench domain models."""

from patchbench.domain.aggregation import (
    ExperimentAggregationError,
    aggregate_runs,
)
from patchbench.domain.comparison import (
    PassFailComparison,
    PassFailComparisonError,
    compare_pass_fail_runs,
)
from patchbench.domain.failure import (
    FailureAnalysis,
    FailureCategory,
    classify_run_failure,
)
from patchbench.domain.models import (
    AgentExecutionMetadata,
    ArtifactPaths,
    EvaluationCaseEvidence,
    EvaluationEvidence,
    PatchFileSummary,
    PatchSummary,
    EvaluationConfig,
    EvaluationResult,
    ExperimentAggregate,
    ExperimentConfiguration,
    ExperimentRecord,
    ReplayRecord,
    RepositoryConfig,
    RunProvenance,
    RunRecord,
    Sha256Hex,
    RunStatus,
    TaskMetadata,
    TaskPromptConfig,
    TaskSpec,
)

from patchbench.domain.provenance import compute_task_fingerprint

from patchbench.domain.evidence_errors import EvidenceParsingError
from patchbench.domain.patch_evidence import summarize_patch
from patchbench.domain.evaluation_evidence import render_evaluation_log, summarize_evaluation_log

from patchbench.domain.analysis import ExperimentAnalysis, RunEvidence
from patchbench.domain.diagnosis import (
    DiagnosisSourcePolicy,
    BundleProvenance,
    DiagnosisCertainty,
    DiagnosisEvidenceBundle,
    DiagnosisHypothesis,
    DiagnosisMode,
    DiagnosisRoute,
    DiagnosisRoutingDecision,
    DiagnosisRoutingReason,
    EvidenceItem,
    EvidenceKind,
    EvidenceOwner,
    EvidenceRef,
    EvidenceSourceState,
    FailureDiagnosis,
    FailureFamily,
    PeerProvenance,
    SubjectProvenance,
    route_run_diagnosis,
)

from patchbench.domain.diagnosis_integrity import (
    canonical_json_bytes, compute_bundle_sha256, compute_diagnosis_sha256,
)
from patchbench.domain.diagnosis_audit import (
    DiagnosisAuditIssueCode, DiagnosisReferenceRole, DiagnosisAuditIssue,
    DiagnosisAuditResult, audit_failure_diagnosis,
)

from patchbench.domain.diagnosis_execution import (
    DiagnosisExternalLLMPolicy, DiagnosisProviderUsage, DiagnosisProviderSettings,
    DiagnosisProviderProvenance, DiagnosisExecutionRecord, compute_execution_sha256,
    DiagnosisPromptTemplateVersion,
)
from patchbench.domain.diagnosis_validation import (
    DiagnosisGoldCase, DiagnosisOverclaimReview, DiagnosisRouteScore,
    ForbiddenClaim, GoldEvidenceLocator, GoldEvidenceRequirement,
    SemanticDiagnosisGold, SemanticDiagnosisScore,
)
from patchbench.domain.diagnosis_metrics import (
    BlindContrastiveComparison, DiagnosisRouteAggregate, MetricMean, MetricRatio,
    PairedDiagnosisDelta, PairTransition, PairTransitionSummary,
    RequiredEvidenceTransitionSummary, SemanticDiagnosisAggregate,
)
from patchbench.domain.diagnosis_suite import (
    DiagnosisValidationFreezeManifest, DiagnosisValidationSuite,
    DiagnosisValidationSuiteCase, DiagnosisValidationSuiteCaseFile,
    FrozenValidationFile, compute_diagnosis_validation_suite_sha256,
)

__all__ = [
    "DiagnosisValidationFreezeManifest",
    "DiagnosisValidationSuite",
    "DiagnosisValidationSuiteCase",
    "DiagnosisValidationSuiteCaseFile",
    "FrozenValidationFile",
    "compute_diagnosis_validation_suite_sha256",
    "BlindContrastiveComparison",
    "DiagnosisRouteAggregate",
    "MetricMean",
    "MetricRatio",
    "PairedDiagnosisDelta",
    "PairTransition",
    "PairTransitionSummary",
    "RequiredEvidenceTransitionSummary",
    "SemanticDiagnosisAggregate",
    "DiagnosisGoldCase",
    "DiagnosisOverclaimReview",
    "DiagnosisRouteScore",
    "ForbiddenClaim",
    "GoldEvidenceLocator",
    "GoldEvidenceRequirement",
    "SemanticDiagnosisGold",
    "SemanticDiagnosisScore",
    "DiagnosisPromptTemplateVersion",
    "DiagnosisExternalLLMPolicy",
    "DiagnosisProviderUsage",
    "DiagnosisProviderSettings",
    "DiagnosisProviderProvenance",
    "DiagnosisExecutionRecord",
    "compute_execution_sha256",
    "canonical_json_bytes",
    "compute_bundle_sha256",
    "compute_diagnosis_sha256",
    "DiagnosisAuditIssueCode",
    "DiagnosisReferenceRole",
    "DiagnosisAuditIssue",
    "DiagnosisAuditResult",
    "audit_failure_diagnosis",
    "DiagnosisSourcePolicy",
    "BundleProvenance",
    "DiagnosisCertainty",
    "DiagnosisEvidenceBundle",
    "DiagnosisHypothesis",
    "DiagnosisMode",
    "DiagnosisRoute",
    "DiagnosisRoutingDecision",
    "DiagnosisRoutingReason",
    "EvidenceItem",
    "EvidenceKind",
    "EvidenceOwner",
    "EvidenceRef",
    "EvidenceSourceState",
    "FailureDiagnosis",
    "FailureFamily",
    "PeerProvenance",
    "SubjectProvenance",
    "route_run_diagnosis",
    "ExperimentAnalysis",
    "RunEvidence",
    "EvidenceParsingError",
    "EvaluationCaseEvidence",
    "EvaluationEvidence",
    "PatchFileSummary",
    "PatchSummary",
    "summarize_patch",
    "render_evaluation_log",
    "summarize_evaluation_log",
    "AgentExecutionMetadata",
    "ArtifactPaths",
    "EvaluationConfig",
    "EvaluationResult",
    "ExperimentAggregate",
    "ExperimentAggregationError",
    "ExperimentConfiguration",
    "ExperimentRecord",
    "FailureAnalysis",
    "FailureCategory",
    "PassFailComparison",
    "PassFailComparisonError",
    "RepositoryConfig",
    "ReplayRecord",
    "RunProvenance",
    "RunRecord",
    "Sha256Hex",
    "RunStatus",
    "TaskMetadata",
    "TaskPromptConfig",
    "TaskSpec",
    "compute_task_fingerprint",
    "aggregate_runs",
    "classify_run_failure",
    "compare_pass_fail_runs",
]
